help_text = ["Playback controls:",
"  p               Toggle pause/play",
"  s               Stop",
"  n               Next song",
"  p               Previous song",
"  >               Seek forward",
"  <               Seek backward",
"  0-9             Seek (0 - 90%) in song",
"",
"Tbmpcy controls:",
"  :               Show command line",
"  h               Show this message",
"  Tab             Switch between playlist / browser",
"  q               Quit",
"",
"Playlist controls:",
"  j, Arrow down   Select next song",
"  k, Arrow up     Select previous song",
"  g               Select first song",
"  G               Select last song",
"  C               Clear playlist",
"  d               Delete playlist item",
"  Return          Play selected song",
"  /               Start search mode",
"  Escape          Clear search",
"  f[C]            Find next item that starts with C",
"                  (e.g. fn for Neil Young - War Of Man)",
"",
"Browser controls:",
"  j, Arrow down   Select next item",
"  k, Arrow up     Select previous item",
"  g               Select first item",
"  G               Select last item",
"  Return          Enter directory / play song",
"  Space           Add directory / song to playlist",
"  u, Backspace    Go to previous directory",
"  U               Update the current directory",
"  /               Start search mode",
"  Escape          Clear search",
"  f[C]            Find next item that starts with C",
"                  (e.g. fn for Neil Young/)"]
